---
.travis.yml:
  secure: "afO7v8HsmULSTuhn7QtSdm8C+N94sQK4MCx2eIptnjq5GH8AkajgIeo2Nv1DOP17oXBoCDwTOt6FEWEKD1P80WSA10Wa6OBKhlaoQmqKjFpSi+WNIPXLFekdXCJL5R6eLnglYHozTuIzEqB3ycxgphbim8+9fpbK4Uto3gNVDV0zVBLuyk9Se0xV9kSBwcQWpfvofx5/TOZOrxo/lDb3SbYPgqtjJYaEI91SmMom9kO9bzEn2gM2WUya+6vL4UxuzZmdlB5d8O6o1O5Vq1s2dJqoz7sY4CnMaRHhV01FQiqGtPwJ53bYYu2cAhXajL2ROPYLQTt+up32ZnCNL2zWQ4+OwTb7I/vR2uPEROTnP9eLEU2EaMXV0ajY1pP0SnD/zMMkEmcsAKRPX+yD8IsvlXri+dIJY+ftvSxhm328xGTb7Oz4MgU6m0qTgo9RMPHp59hTu4QaoKMTEmHwSFoZ/ilk47+qyNrk20wT6PAYDm28/3+9jz6YQefc1RjbNjnD7szuU0LozUVWpucjhEXGlYT58BjwIPPYu4qHehQJkS9B6/U9AIenef7Hledqh9lng918Fao3rDhUs672PmchzgN7Cwiem8ngkvtSG4SJSaATEMKiecaI1ABs0SQYoAmCapTn/eWRTbSIYNFpvfyAWG0kipAGBOtsJtmrysSFfy8="
  docker_sets:
    - set: centos7-64
    - set: ubuntu1604-64
    - set: debian8-64
